<a href="https://colab.research.google.com/github/guilhermeterenciani/IA/blob/main/08_first_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torchsummary

In [6]:
conv1 = nn.Sequential(nn.Conv2d(in_channels = 1, out_channels = 6, kernel_size=5))

In [9]:

              # batch, canais, comprimento, altura
x = torch.randn((1,1,32,32))

In [10]:
pred = conv1(x)

In [11]:
pred.shape

torch.Size([1, 6, 28, 28])

In [13]:
torchsummary.summary(conv1,(1,32,32))


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1            [-1, 6, 28, 28]             156
Total params: 156
Trainable params: 156
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.04
Params size (MB): 0.00
Estimated Total Size (MB): 0.04
----------------------------------------------------------------


In [14]:
conv2 = nn.Sequential(nn.Conv2d(in_channels = 6, out_channels = 16, kernel_size=5))

In [15]:
torchsummary.summary(conv2,(6,14,14))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 16, 10, 10]           2,416
Total params: 2,416
Trainable params: 2,416
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.01
Params size (MB): 0.01
Estimated Total Size (MB): 0.03
----------------------------------------------------------------


In [16]:
5*5*6*16 + 16

2416

In [21]:
conv1 = nn.Sequential(nn.Conv2d(in_channels = 1, out_channels = 6, kernel_size=5))
pool = nn.MaxPool2d(kernel_size=2,stride=2)
conv2 = nn.Sequential(nn.Conv2d(in_channels = 6, out_channels = 16, kernel_size=5))


In [ ]:
# batch, canais, comprimento, altura
x = torch.randn((1,1,32,32))

In [22]:
s1 = conv1(x)

In [23]:
s1.shape

torch.Size([1, 6, 28, 28])

In [24]:
s2 = pool(s1)

In [25]:
s2.shape

torch.Size([1, 6, 14, 14])

In [26]:
s3 = conv2(s2)

In [28]:
s3.shape

torch.Size([1, 16, 10, 10])

In [29]:
s4 = pool(s3)

In [30]:
s4.shape

torch.Size([1, 16, 5, 5])

In [49]:
linear1 = nn.Linear(in_features=16*5*5,out_features=120)
linear2 = nn.Linear(in_features=120,out_features=84)
linear3 = nn.Linear(in_features=84,out_features=10)
flatten = nn.Flatten()

In [34]:
s5 = s4.flatten()

In [35]:
s6 = linear1(s5)

In [36]:
s6.shape

torch.Size([120])

In [37]:
s7 = linear2(s6)

In [38]:
s7.shape

torch.Size([84])

In [39]:
s8 = linear3(s7)

In [40]:
s8.shape

torch.Size([10])

In [41]:
s8

tensor([-0.0159, -0.1606, -0.1038, -0.0951,  0.1066, -0.1176,  0.1290, -0.0581,
         0.0087,  0.0824], grad_fn=<AddBackward0>)

In [42]:
relu = nn.ReLU()

In [50]:
              # batch, canais, comprimento, altura
x = torch.randn((1,1,32,32))

In [51]:
x = relu(conv1(x))
x = pool(x)
x = relu(conv2(x))
x = pool(x)
x = flatten(x)
x = relu(linear1(x))
x = relu(linear2(x))
x = relu(linear3(x))

In [52]:
x

tensor([[0.0000, 0.0000, 0.1711, 0.0529, 0.0000, 0.0000, 0.0489, 0.0462, 0.0000,
         0.0000]], grad_fn=<ReluBackward0>)

In [53]:
model = nn.Sequential(
    nn.Conv2d(in_channels = 1, out_channels = 6, kernel_size=5),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2,stride=2),
    nn.Conv2d(in_channels = 6, out_channels = 16, kernel_size=5),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2,stride=2),
    nn.Flatten(),
    nn.Linear(400, 120),
    nn.ReLU(),
    nn.Linear(120,84),
    nn.ReLU(),
    nn.Linear(84,10),

)


In [55]:
x = torch.randn((1,1,32,32))
pred = model(x)

In [58]:
pred

tensor([[ 0.1090,  0.0762, -0.0943, -0.1371, -0.0409, -0.0151, -0.0168,  0.0386,
         -0.0558,  0.0496]], grad_fn=<AddmmBackward0>)

In [59]:
torchsummary.summary(model,(1,32,32))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1            [-1, 6, 28, 28]             156
              ReLU-2            [-1, 6, 28, 28]               0
         MaxPool2d-3            [-1, 6, 14, 14]               0
            Conv2d-4           [-1, 16, 10, 10]           2,416
              ReLU-5           [-1, 16, 10, 10]               0
         MaxPool2d-6             [-1, 16, 5, 5]               0
           Flatten-7                  [-1, 400]               0
            Linear-8                  [-1, 120]          48,120
              ReLU-9                  [-1, 120]               0
           Linear-10                   [-1, 84]          10,164
             ReLU-11                   [-1, 84]               0
           Linear-12                   [-1, 10]             850
Total params: 61,706
Trainable params: 61,706
Non-trainable params: 0
---------------------------------