<a href="https://colab.research.google.com/github/guilhermeterenciani/IA/blob/main/15_bert_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 34.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 41.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 105.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 90.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 40.4 MB/s eta 0:00:00


In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("pucpr-br/cardiobertpt")
model = AutoModelForMaskedLM.from_pretrained("pucpr-br/cardiobertpt")

In [ ]:
tokenizer.tokenize("Isso é um teste")

['Isso', 'é', 'um', 'teste']

In [ ]:
tokenizer("Isso é um teste")

{'input_ids': [101, 70646, 263, 10293, 62574, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1]}

In [ ]:
model

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_

In [ ]:
import torch

In [ ]:
emb_isso = model.bert.embeddings.word_embeddings(torch.tensor([[70646]]))

In [ ]:
model.bert.encoder.layer[0]

BertLayer(
  (attention): BertAttention(
    (self): BertSelfAttention(
      (query): Linear(in_features=768, out_features=768, bias=True)
      (key): Linear(in_features=768, out_features=768, bias=True)
      (value): Linear(in_features=768, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (output): BertSelfOutput(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (intermediate): BertIntermediate(
    (dense): Linear(in_features=768, out_features=3072, bias=True)
    (intermediate_act_fn): GELUActivation()
  )
  (output): BertOutput(
    (dense): Linear(in_features=3072, out_features=768, bias=True)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
)

In [ ]:
model.bert.encoder.layer[0].attention

BertAttention(
  (self): BertSelfAttention(
    (query): Linear(in_features=768, out_features=768, bias=True)
    (key): Linear(in_features=768, out_features=768, bias=True)
    (value): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (output): BertSelfOutput(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
)

In [ ]:
model.bert.encoder.layer[0].attention(emb_isso)[0].shape

torch.Size([1, 1, 768])

In [ ]:
model.bert.encoder.layer[0].attention.self.query(emb_isso).shape

torch.Size([1, 1, 768])

In [ ]:
temb = torch.nn.Embedding(1000,10)

In [ ]:
temb(torch.tensor([0]))

tensor([[ 0.4703,  0.3260,  0.9225,  0.5105,  0.5573, -0.8196,  1.2163, -0.4415,
         -0.3177,  1.7366]], grad_fn=<EmbeddingBackward0>)

In [ ]:
model.bert

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(119547, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
 

In [ ]:
import torch

In [ ]:
palavras = ['estudante','professor','faculdade','universidade','mãe','pai']

In [ ]:
ids = []
for palavra in palavras:
    print(tokenizer.tokenize(palavra),tokenizer(palavra)['input_ids'][1])
    ids.append(tokenizer(palavra)['input_ids'][1])

['est', '##udan', '##te'] 10176
['professor'] 13853
['fac', '##uld', '##ade'] 107159
['universidade'] 96885
['mãe'] 36937
['pai'] 22341


In [ ]:
emb = model.bert.embeddings.word_embeddings(torch.tensor(ids))

In [ ]:
emb

tensor([[-0.0152, -0.0084,  0.0113,  ..., -0.0127, -0.0808, -0.0060],
        [ 0.0320, -0.0543,  0.0095,  ..., -0.0670, -0.0483, -0.0351],
        [ 0.0030, -0.0339, -0.0127,  ...,  0.0089, -0.0002, -0.0142],
        [ 0.0124, -0.0240, -0.0256,  ..., -0.0218, -0.0538, -0.0745],
        [-0.0395, -0.0298,  0.0126,  ..., -0.0259,  0.0301, -0.0391],
        [-0.0533, -0.0274, -0.0647,  ...,  0.0264, -0.0258, -0.0632]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
import numpy as np

In [ ]:
np.array(emb.tolist())

array([[-0.01518316, -0.00835827,  0.01128831, ..., -0.01267184,
        -0.08076517, -0.00600482],
       [ 0.03199208, -0.05429307,  0.00952279, ..., -0.06703734,
        -0.0482999 , -0.03512437],
       [ 0.00301066, -0.03389924, -0.01273983, ...,  0.00886524,
        -0.00024165, -0.01416928],
       [ 0.01240964, -0.0240491 , -0.02560527, ..., -0.02183383,
        -0.0538496 , -0.07447419],
       [-0.03950155, -0.02977407,  0.01260252, ..., -0.02588004,
         0.03014963, -0.03907271],
       [-0.05327621, -0.02739476, -0.06466088, ...,  0.02642308,
        -0.02582313, -0.06321026]])

In [ ]:
X =  np.array(emb.tolist())

In [ ]:
from sklearn.neighbors import NearestNeighbors

In [ ]:
neigh = NearestNeighbors(n_neighbors=2).fit(X)

In [ ]:
neigh.kneighbors(X)

(array([[3.65002415e-08, 1.44710746e+00],
        [3.65002415e-08, 1.31544017e+00],
        [3.65002415e-08, 1.48470605e+00],
        [4.21468485e-08, 1.35081889e+00],
        [3.65002415e-08, 1.19447464e+00],
        [2.98023224e-08, 1.19447464e+00]]),
 array([[0, 4],
        [1, 4],
        [2, 1],
        [3, 4],
        [4, 5],
        [5, 4]]))

In [ ]:
neigh.kneighbors_graph(X).toarray()

array([[1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [ ]:
from transformers import GPTNeoForCausalLM, GPT2Tokenizer
model = GPTNeoForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")
tokenizer = GPT2Tokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")