<a href="https://colab.research.google.com/github/guilhermeterenciani/IA/blob/main/15_bert_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 31.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 26.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 44.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 49.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 30.1 MB/s eta 0:00:00


In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("AVSilva/bertimbau-large-fine-tuned-md")
model = AutoModelForMaskedLM.from_pretrained("AVSilva/bertimbau-large-fine-tuned-md")

In [ ]:
import torch

In [ ]:
palavras = ['estudante','professor','faculdade','universidade','mãe','pai']

In [ ]:
ids = []
for palavra in palavras:
    print(tokenizer.tokenize(palavra),tokenizer(palavra)['input_ids'][1])
    ids.append(tokenizer(palavra)['input_ids'][1])

['estudante'] 8609
['professor'] 2917
['faculdade'] 8558
['universidade'] 6480
['mãe'] 2196
['pai'] 1568


In [ ]:
emb = model.bert.embeddings.word_embeddings(torch.tensor(ids))

In [ ]:
emb

tensor([[-0.0593,  0.0416,  0.0313,  ...,  0.0053,  0.0565,  0.0831],
        [-0.0056, -0.0361,  0.0253,  ..., -0.0547,  0.1452,  0.0239],
        [ 0.0206,  0.0257, -0.0035,  ..., -0.0107, -0.0240, -0.0105],
        [ 0.0253,  0.0403,  0.0045,  ...,  0.0333,  0.0403, -0.0851],
        [ 0.0375,  0.0189, -0.0527,  ..., -0.0396,  0.0476,  0.0438],
        [ 0.0448, -0.0215, -0.0278,  ..., -0.0024,  0.0762,  0.0352]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
import numpy as np

In [ ]:
np.array(emb.tolist())

array([[-0.05933865,  0.0415671 ,  0.03130454, ...,  0.00533059,
         0.05649181,  0.08313181],
       [-0.0056343 , -0.03608444,  0.02527579, ..., -0.05469749,
         0.14524789,  0.02391756],
       [ 0.02057093,  0.02569926, -0.00348592, ..., -0.01067314,
        -0.02399218, -0.01053104],
       [ 0.02527398,  0.04033869,  0.00451437, ...,  0.03327486,
         0.04033491, -0.08509812],
       [ 0.03752715,  0.0188881 , -0.05273628, ..., -0.03956173,
         0.04760795,  0.04380529],
       [ 0.04480895, -0.02149872, -0.0278208 , ..., -0.00238544,
         0.07620648,  0.03523555]])

In [ ]:
X =  np.array(emb.tolist())

In [ ]:
from sklearn.neighbors import NearestNeighbors

In [ ]:
neigh = NearestNeighbors(n_neighbors=2).fit(X)

In [ ]:
neigh.kneighbors(X)

(array([[2.98023224e-08, 1.25361538e+00],
        [2.10734243e-08, 1.25361538e+00],
        [5.16191366e-08, 1.18088866e+00],
        [2.98023224e-08, 1.18088866e+00],
        [2.98023224e-08, 1.16519303e+00],
        [3.65002415e-08, 1.16519303e+00]]),
 array([[0, 1],
        [1, 0],
        [2, 3],
        [3, 2],
        [4, 5],
        [5, 4]]))

In [ ]:
neigh.kneighbors_graph(X).toarray()

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [ ]:
from transformers import GPTNeoForCausalLM, GPT2Tokenizer
model = GPTNeoForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")
tokenizer = GPT2Tokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")