<a href="https://colab.research.google.com/github/guilhermeterenciani/IA/blob/main/18_masked_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
T = 10

In [ ]:
tril = torch.tril(torch.ones(T, T))

In [ ]:
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
wei = torch.arange(100).float().view((10,10))

In [ ]:
wei

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
        [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
        [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
        [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
        [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [ ]:
wei = wei.masked_fill(tril == 0, float('-inf'))

In [ ]:
wei

tensor([[ 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [10., 11., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [20., 21., 22., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [30., 31., 32., 33., -inf, -inf, -inf, -inf, -inf, -inf],
        [40., 41., 42., 43., 44., -inf, -inf, -inf, -inf, -inf],
        [50., 51., 52., 53., 54., 55., -inf, -inf, -inf, -inf],
        [60., 61., 62., 63., 64., 65., 66., -inf, -inf, -inf],
        [70., 71., 72., 73., 74., 75., 76., 77., -inf, -inf],
        [80., 81., 82., 83., 84., 85., 86., 87., 88., -inf],
        [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [ ]:
wei = torch.nn.functional.softmax(wei, dim=-1)

tensor([[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.6894e-01, 7.3106e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.0031e-02, 2.4473e-01, 6.6524e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.2059e-02, 8.7144e-02, 2.3688e-01, 6.4391e-01, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.1656e-02, 3.1685e-02, 8.6129e-02, 2.3412e-01, 6.3641e-01, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.2698e-03, 1.1606e-02, 3.1550e-02, 8.5761e-02, 2.3312e-01, 6.3369e-01,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.5683e-03, 4.2631e-03, 1.1588e-02, 3.1500e-02, 8.5626e-02, 2.3276e-01,
         6.3270e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [5.7661e-04, 1.5674